name: Run FixGuy

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  fixguy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CyberSage5/fixguy@v1.0.5  # Updated to v1.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
