name: Run FixGuy

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  fixguy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the required Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      - uses: CyberSage5/fixguy@v1.0.1  # Updated version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
