name: Run FixGuy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        if [ -f fixguy-action/requirements.txt ]; then
          pip install -r fixguy-action/requirements.txt
          echo "Installed packages:"
          pip list | grep -E "PyGithub|flake8|GitPython"  # Check key packages
        else
          echo "Error: requirements.txt not found in fixguy-action/"
          ls -la fixguy-action/  # Debug file listing
          exit 1
        fi
