name: Run FixGuy

on:
  schedule:
    - cron: "0 0 * * 0"  # Weekly on Sunday
  workflow_dispatch:  # Manual trigger
  push:  # Run on push events
  pull_request:  # Run on pull requests

jobs:
  fixguy:
    runs-on: ubuntu-latest
    steps:
      # Check out the user's repo (fixguy-test)
      - name: Checkout user's repo
        uses: actions/checkout@v4

      # Run FixGuy action (this will handle dependency installation)
      - name: Run FixGuy action
        uses: CyberSage5/fixguy@v1.0.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Fallback step to ensure PyGithub is installed if the action fails
      - name: Fallback install PyGithub
        run: |
          echo "Ensuring PyGithub is installed..."
          pip install PyGithub==2.3.0
          echo "Installed packages:"
          pip list | grep PyGithub
        shell: bash
        if: failure()  # Only run if the previous step fails
